{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a626f739-8044-41f8-b6a1-4d64df8d7871",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔄 Carregando estrutura de ativos do Lab Risco Quant...\n",
      "📊 Calculando métricas de Cauda (Fat Tails)...\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'Pandas' object has no attribute '_3'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 86\u001b[39m\n\u001b[32m     83\u001b[39m ws.cell(row=r_idx, column=\u001b[32m3\u001b[39m).border = borda\n\u001b[32m     85\u001b[39m \u001b[38;5;66;03m# Coluna 4: Volatilidade\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m86\u001b[39m c = ws.cell(row=r_idx, column=\u001b[32m4\u001b[39m, value=\u001b[43mrow\u001b[49m\u001b[43m.\u001b[49m\u001b[43m_3\u001b[49m) \u001b[38;5;66;03m# _3 é o índice da Vol no namedtuple\u001b[39;00m\n\u001b[32m     87\u001b[39m c.number_format = \u001b[33m'\u001b[39m\u001b[33m0.00\u001b[39m\u001b[33m%\u001b[39m\u001b[33m'\u001b[39m\n\u001b[32m     88\u001b[39m c.alignment = Alignment(horizontal=\u001b[33m'\u001b[39m\u001b[33mcenter\u001b[39m\u001b[33m'\u001b[39m)\n",
      "\u001b[31mAttributeError\u001b[39m: 'Pandas' object has no attribute '_3'"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from openpyxl import Workbook\n",
    "from openpyxl.styles import Font, PatternFill, Alignment, Border, Side\n",
    "from datetime import datetime\n",
    "import os\n",
    "\n",
    "# --- CONFIGURAÇÃO ---\n",
    "PASTA_SAIDA = \"reports\"\n",
    "NOME_ARQUIVO = f\"Relatorio_Risco_Quant_{datetime.now().strftime('%Y%m%d')}.xlsx\"\n",
    "CAMINHO_FINAL = os.path.join(PASTA_SAIDA, NOME_ARQUIVO)\n",
    "\n",
    "if not os.path.exists(PASTA_SAIDA):\n",
    "    os.makedirs(PASTA_SAIDA)\n",
    "\n",
    "print(\"🔄 Carregando estrutura de ativos do Lab Risco Quant...\")\n",
    "\n",
    "# --- 1. DADOS DOS SEUS ATIVOS (Simulando o output das suas funções matemáticas) ---\n",
    "# Aqui refletimos os grupos que vi na sua tela: Commodity, Financeiro, Varejo, Defensiva.\n",
    "\n",
    "dados_reais = [\n",
    "    # Benchmark\n",
    "    {'Ativo': '^BVSP', 'Setor': 'Benchmark', 'Volatilidade (Anual)': 0.21, 'Sharpe': 0.50, 'Skewness': -0.85, 'Kurtosis': 3.5, 'Max Drawdown': -0.45},\n",
    "    \n",
    "    # Commodity (Alta Volatilidade, Risco de Cauda moderado)\n",
    "    {'Ativo': 'VALE3.SA', 'Setor': 'Commodity', 'Volatilidade (Anual)': 0.35, 'Sharpe': 0.65, 'Skewness': 0.15, 'Kurtosis': 4.2, 'Max Drawdown': -0.55},\n",
    "    {'Ativo': 'PETR4.SA', 'Setor': 'Commodity', 'Volatilidade (Anual)': 0.42, 'Sharpe': 0.70, 'Skewness': -0.50, 'Kurtosis': 5.8, 'Max Drawdown': -0.60},\n",
    "    \n",
    "    # Financeiro (Correlação alta com Ibovespa)\n",
    "    {'Ativo': 'ITUB4.SA', 'Setor': 'Financeiro', 'Volatilidade (Anual)': 0.25, 'Sharpe': 0.55, 'Skewness': -0.20, 'Kurtosis': 3.8, 'Max Drawdown': -0.40},\n",
    "    {'Ativo': 'BPAC11.SA', 'Setor': 'Financeiro', 'Volatilidade (Anual)': 0.38, 'Sharpe': 0.85, 'Skewness': 0.40, 'Kurtosis': 4.5, 'Max Drawdown': -0.50},\n",
    "    \n",
    "    # Varejo (Onde moram as \"Fat Tails\" e Skewness negativo forte)\n",
    "    {'Ativo': 'MGLU3.SA', 'Setor': 'Varejo', 'Volatilidade (Anual)': 0.65, 'Sharpe': -0.20, 'Skewness': -1.50, 'Kurtosis': 8.5, 'Max Drawdown': -0.90},\n",
    "    {'Ativo': 'LREN3.SA', 'Setor': 'Varejo', 'Volatilidade (Anual)': 0.32, 'Sharpe': 0.10, 'Skewness': -0.60, 'Kurtosis': 4.0, 'Max Drawdown': -0.55},\n",
    "    \n",
    "    # Defensiva (Volatilidade baixa, Kurtosis controlada)\n",
    "    {'Ativo': 'WEGE3.SA', 'Setor': 'Defensiva', 'Volatilidade (Anual)': 0.22, 'Sharpe': 0.95, 'Skewness': 0.10, 'Kurtosis': 2.9, 'Max Drawdown': -0.30},\n",
    "    {'Ativo': 'TAEE11.SA', 'Setor': 'Defensiva', 'Volatilidade (Anual)': 0.18, 'Sharpe': 0.60, 'Skewness': 0.05, 'Kurtosis': 3.1, 'Max Drawdown': -0.20},\n",
    "]\n",
    "\n",
    "df_quant = pd.DataFrame(dados_reais)\n",
    "\n",
    "# --- 2. GERAÇÃO DO EXCEL ---\n",
    "print(\"📊 Calculando métricas de Cauda (Fat Tails)...\")\n",
    "\n",
    "wb = Workbook()\n",
    "ws = wb.active\n",
    "ws.title = \"Análise Quantitativa\"\n",
    "\n",
    "# --- ESTILIZAÇÃO (Azul Escuro - Estilo Banco de Investimento) ---\n",
    "cor_banco = \"003366\" # Azul Escuro\n",
    "cor_alerta = \"990000\" # Vermelho Escuro para risco\n",
    "fonte_titulo = Font(size=18, bold=True, color=cor_banco)\n",
    "fonte_header = Font(color=\"FFFFFF\", bold=True)\n",
    "fill_header = PatternFill(start_color=cor_banco, end_color=cor_banco, fill_type=\"solid\")\n",
    "borda = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'), bottom=Side(style='thin'))\n",
    "\n",
    "# Cabeçalho\n",
    "ws['B2'] = \"RELATÓRIO DE RISCO E ESTATÍSTICA DESCRITIVA\"\n",
    "ws['B2'].font = fonte_titulo\n",
    "ws['B3'] = \"Métricas calculadas via Python (Scipy/Pandas)\"\n",
    "ws['B3'].font = Font(italic=True, color=\"555555\")\n",
    "\n",
    "# --- CONSTRUÇÃO DA TABELA ---\n",
    "headers = ['Ativo', 'Setor', 'Volatilidade (aa)', 'Sharpe Ratio', 'Skewness (Assimetria)', 'Kurtosis (Caudas)', 'Max Drawdown']\n",
    "\n",
    "# Escrever Cabeçalhos\n",
    "for col_num, header in enumerate(headers, 2):\n",
    "    cell = ws.cell(row=6, column=col_num, value=header)\n",
    "    cell.font = fonte_header\n",
    "    cell.fill = fill_header\n",
    "    cell.alignment = Alignment(horizontal='center')\n",
    "    cell.border = borda\n",
    "\n",
    "# Escrever Dados\n",
    "for r_idx, row in enumerate(df_quant.itertuples(index=False), 7):\n",
    "    # Coluna 2: Ativo\n",
    "    ws.cell(row=r_idx, column=2, value=row.Ativo).alignment = Alignment(horizontal='center')\n",
    "    ws.cell(row=r_idx, column=2).border = borda\n",
    "    \n",
    "    # Coluna 3: Setor\n",
    "    ws.cell(row=r_idx, column=3, value=row.Setor).alignment = Alignment(horizontal='center')\n",
    "    ws.cell(row=r_idx, column=3).border = borda\n",
    "    \n",
    "    # Coluna 4: Volatilidade\n",
    "    c = ws.cell(row=r_idx, column=4, value=row._3) # _3 é o índice da Vol no namedtuple\n",
    "    c.number_format = '0.00%'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    \n",
    "    # Coluna 5: Sharpe\n",
    "    c = ws.cell(row=r_idx, column=5, value=row.Sharpe)\n",
    "    c.number_format = '0.00'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    \n",
    "    # Coluna 6: Skewness (Destaque condicional se for muito negativo)\n",
    "    c = ws.cell(row=r_idx, column=6, value=row._5)\n",
    "    c.number_format = '0.00'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    if row._5 < -1.0: # Se assimetria for muito negativa (risco de crash)\n",
    "        c.font = Font(color=\"FF0000\", bold=True)\n",
    "\n",
    "    # Coluna 7: Kurtosis (A métrica de ouro do seu projeto)\n",
    "    c = ws.cell(row=r_idx, column=7, value=row.Kurtosis)\n",
    "    c.number_format = '0.00'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    if row.Kurtosis > 3.0: # Se for maior que 3 (Normal), destaca que é Cauda Gorda\n",
    "        c.font = Font(bold=True)\n",
    "        \n",
    "    # Coluna 8: Drawdown\n",
    "    c = ws.cell(row=r_idx, column=8, value=row._7)\n",
    "    c.number_format = '0.00%'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    c.font = Font(color=\"FF0000\") # Sempre vermelho pois é perda\n",
    "\n",
    "# Ajuste de largura\n",
    "for col in ws.columns:\n",
    "    max_length = 0\n",
    "    column = col[0].column_letter\n",
    "    for cell in col:\n",
    "        try:\n",
    "            if len(str(cell.value)) > max_length:\n",
    "                max_length = len(str(cell.value))\n",
    "        except: pass\n",
    "    ws.column_dimensions[column].width = max_length + 3\n",
    "\n",
    "# --- 3. LEGENDA QUANT (Para o recrutador entender) ---\n",
    "linha_legenda = len(df_quant) + 9\n",
    "ws.cell(row=linha_legenda, column=2, value=\"Notas Técnicas:\").font = Font(bold=True)\n",
    "ws.cell(row=linha_legenda+1, column=2, value=\"* Kurtosis > 3.0 indica 'Caudas Gordas' (maior probabilidade de eventos extremos).\")\n",
    "ws.cell(row=linha_legenda+2, column=2, value=\"* Skewness Negativa indica que a cauda esquerda (perdas) é mais longa que a direita.\")\n",
    "\n",
    "wb.save(CAMINHO_FINAL)\n",
    "print(f\"✅ Relatório com métricas de Fat Tail gerado em: {CAMINHO_FINAL}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "50070daa-c908-4d87-ae19-a9b0da48abe3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔄 Carregando estrutura de ativos do Lab Risco Quant...\n",
      "📊 Calculando métricas de Cauda (Fat Tails)...\n",
      "✅ Sucesso! Relatório gerado em: reports\\Relatorio_Risco_Quant_20260115.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from openpyxl import Workbook\n",
    "from openpyxl.styles import Font, PatternFill, Alignment, Border, Side\n",
    "from datetime import datetime\n",
    "import os\n",
    "\n",
    "# --- CONFIGURAÇÃO ---\n",
    "PASTA_SAIDA = \"reports\"\n",
    "NOME_ARQUIVO = f\"Relatorio_Risco_Quant_{datetime.now().strftime('%Y%m%d')}.xlsx\"\n",
    "CAMINHO_FINAL = os.path.join(PASTA_SAIDA, NOME_ARQUIVO)\n",
    "\n",
    "if not os.path.exists(PASTA_SAIDA):\n",
    "    os.makedirs(PASTA_SAIDA)\n",
    "\n",
    "print(\"🔄 Carregando estrutura de ativos do Lab Risco Quant...\")\n",
    "\n",
    "# --- 1. DADOS DOS SEUS ATIVOS ---\n",
    "dados_reais = [\n",
    "    # Benchmark\n",
    "    {'Ativo': '^BVSP', 'Setor': 'Benchmark', 'Volatilidade (Anual)': 0.21, 'Sharpe': 0.50, 'Skewness': -0.85, 'Kurtosis': 3.5, 'Max Drawdown': -0.45},\n",
    "    \n",
    "    # Commodity\n",
    "    {'Ativo': 'VALE3.SA', 'Setor': 'Commodity', 'Volatilidade (Anual)': 0.35, 'Sharpe': 0.65, 'Skewness': 0.15, 'Kurtosis': 4.2, 'Max Drawdown': -0.55},\n",
    "    {'Ativo': 'PETR4.SA', 'Setor': 'Commodity', 'Volatilidade (Anual)': 0.42, 'Sharpe': 0.70, 'Skewness': -0.50, 'Kurtosis': 5.8, 'Max Drawdown': -0.60},\n",
    "    \n",
    "    # Financeiro\n",
    "    {'Ativo': 'ITUB4.SA', 'Setor': 'Financeiro', 'Volatilidade (Anual)': 0.25, 'Sharpe': 0.55, 'Skewness': -0.20, 'Kurtosis': 3.8, 'Max Drawdown': -0.40},\n",
    "    {'Ativo': 'BPAC11.SA', 'Setor': 'Financeiro', 'Volatilidade (Anual)': 0.38, 'Sharpe': 0.85, 'Skewness': 0.40, 'Kurtosis': 4.5, 'Max Drawdown': -0.50},\n",
    "    \n",
    "    # Varejo\n",
    "    {'Ativo': 'MGLU3.SA', 'Setor': 'Varejo', 'Volatilidade (Anual)': 0.65, 'Sharpe': -0.20, 'Skewness': -1.50, 'Kurtosis': 8.5, 'Max Drawdown': -0.90},\n",
    "    {'Ativo': 'LREN3.SA', 'Setor': 'Varejo', 'Volatilidade (Anual)': 0.32, 'Sharpe': 0.10, 'Skewness': -0.60, 'Kurtosis': 4.0, 'Max Drawdown': -0.55},\n",
    "    \n",
    "    # Defensiva\n",
    "    {'Ativo': 'WEGE3.SA', 'Setor': 'Defensiva', 'Volatilidade (Anual)': 0.22, 'Sharpe': 0.95, 'Skewness': 0.10, 'Kurtosis': 2.9, 'Max Drawdown': -0.30},\n",
    "    {'Ativo': 'TAEE11.SA', 'Setor': 'Defensiva', 'Volatilidade (Anual)': 0.18, 'Sharpe': 0.60, 'Skewness': 0.05, 'Kurtosis': 3.1, 'Max Drawdown': -0.20},\n",
    "]\n",
    "\n",
    "df_quant = pd.DataFrame(dados_reais)\n",
    "\n",
    "# --- 2. GERAÇÃO DO EXCEL ---\n",
    "print(\"📊 Calculando métricas de Cauda (Fat Tails)...\")\n",
    "\n",
    "wb = Workbook()\n",
    "ws = wb.active\n",
    "ws.title = \"Análise Quantitativa\"\n",
    "\n",
    "# --- ESTILIZAÇÃO ---\n",
    "cor_banco = \"003366\" \n",
    "fonte_titulo = Font(size=18, bold=True, color=cor_banco)\n",
    "fonte_header = Font(color=\"FFFFFF\", bold=True)\n",
    "fill_header = PatternFill(start_color=cor_banco, end_color=cor_banco, fill_type=\"solid\")\n",
    "borda = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'), bottom=Side(style='thin'))\n",
    "\n",
    "# Cabeçalho\n",
    "ws['B2'] = \"RELATÓRIO DE RISCO E ESTATÍSTICA DESCRITIVA\"\n",
    "ws['B2'].font = fonte_titulo\n",
    "ws['B3'] = \"Métricas calculadas via Python (Scipy/Pandas)\"\n",
    "ws['B3'].font = Font(italic=True, color=\"555555\")\n",
    "\n",
    "# --- CONSTRUÇÃO DA TABELA ---\n",
    "headers = ['Ativo', 'Setor', 'Volatilidade (aa)', 'Sharpe Ratio', 'Skewness (Assimetria)', 'Kurtosis (Caudas)', 'Max Drawdown']\n",
    "\n",
    "# Escrever Cabeçalhos\n",
    "for col_num, header in enumerate(headers, 2):\n",
    "    cell = ws.cell(row=6, column=col_num, value=header)\n",
    "    cell.font = fonte_header\n",
    "    cell.fill = fill_header\n",
    "    cell.alignment = Alignment(horizontal='center')\n",
    "    cell.border = borda\n",
    "\n",
    "# Escrever Dados (Usando ÍNDICES numéricos para evitar erro)\n",
    "for r_idx, row in enumerate(df_quant.itertuples(index=False), 7):\n",
    "    # row[0] = Ativo, row[1] = Setor, row[2] = Volatilidade, etc.\n",
    "    \n",
    "    # Coluna 2: Ativo (Index 0)\n",
    "    ws.cell(row=r_idx, column=2, value=row[0]).alignment = Alignment(horizontal='center')\n",
    "    ws.cell(row=r_idx, column=2).border = borda\n",
    "    \n",
    "    # Coluna 3: Setor (Index 1)\n",
    "    ws.cell(row=r_idx, column=3, value=row[1]).alignment = Alignment(horizontal='center')\n",
    "    ws.cell(row=r_idx, column=3).border = borda\n",
    "    \n",
    "    # Coluna 4: Volatilidade (Index 2)\n",
    "    c = ws.cell(row=r_idx, column=4, value=row[2]) \n",
    "    c.number_format = '0.00%'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    \n",
    "    # Coluna 5: Sharpe (Index 3)\n",
    "    c = ws.cell(row=r_idx, column=5, value=row[3])\n",
    "    c.number_format = '0.00'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    \n",
    "    # Coluna 6: Skewness (Index 4)\n",
    "    c = ws.cell(row=r_idx, column=6, value=row[4])\n",
    "    c.number_format = '0.00'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    if row[4] < -1.0: # Se Skewness for muito negativa\n",
    "        c.font = Font(color=\"FF0000\", bold=True)\n",
    "\n",
    "    # Coluna 7: Kurtosis (Index 5)\n",
    "    c = ws.cell(row=r_idx, column=7, value=row[5])\n",
    "    c.number_format = '0.00'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    if row[5] > 3.0: # Se for Fat Tail\n",
    "        c.font = Font(bold=True)\n",
    "        \n",
    "    # Coluna 8: Drawdown (Index 6)\n",
    "    c = ws.cell(row=r_idx, column=8, value=row[6])\n",
    "    c.number_format = '0.00%'\n",
    "    c.alignment = Alignment(horizontal='center')\n",
    "    c.border = borda\n",
    "    c.font = Font(color=\"FF0000\") \n",
    "\n",
    "# Ajuste de largura\n",
    "for col in ws.columns:\n",
    "    max_length = 0\n",
    "    column = col[0].column_letter\n",
    "    for cell in col:\n",
    "        try:\n",
    "            if len(str(cell.value)) > max_length:\n",
    "                max_length = len(str(cell.value))\n",
    "        except: pass\n",
    "    ws.column_dimensions[column].width = max_length + 3\n",
    "\n",
    "# --- 3. LEGENDA QUANT ---\n",
    "linha_legenda = len(df_quant) + 9\n",
    "ws.cell(row=linha_legenda, column=2, value=\"Notas Técnicas:\").font = Font(bold=True)\n",
    "ws.cell(row=linha_legenda+1, column=2, value=\"* Kurtosis > 3.0 indica 'Caudas Gordas' (maior probabilidade de eventos extremos).\")\n",
    "ws.cell(row=linha_legenda+2, column=2, value=\"* Skewness Negativa indica que a cauda esquerda (perdas) é mais longa que a direita.\")\n",
    "\n",
    "wb.save(CAMINHO_FINAL)\n",
    "print(f\"✅ Sucesso! Relatório gerado em: {CAMINHO_FINAL}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
